Models/Customers/MemberCard.cs
using OilTeamProject.Persistence;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading;

namespace OilTeamProject.Models.Customers
{
    public enum MembershipType
    {
        Basic,
        Silver,
        Gold
    }

    public class MemberCard
    {
        [Key]
        [ForeignKey("Customer")]
        public int CustomerID { get; set; }

        [Required]
        public DateTime CreationDate { get; set; }

        [Required]
        [Display(Name = "Type")]
        public MembershipType Type { get; set; }

        [Display(Name = "Code")]
        public string MemberCardCode { get; set; }

        [Required]
        public int Credits { get; set; }

        [Required]
        public bool NewsLetter { get; set; }

        public virtual Customer Customer { get; set; }



        public static string GetMemberCardCode()
        {
            Thread.Sleep(100);
            return DateTime.Now.ToString("MMddHHmmss");
        }

        public static DateTime GetCreationDate()
        {
            MemberCard memberCard = new MemberCard();
            return memberCard.CreationDate = DateTime.Now;
        }

        private static MemberCard GetMemberCard(Customer customer, ApplicationDbContext _context)
        {
            var CustomerMemberCard = _context
                .MemberCards.SingleOrDefault(m => m.CustomerID == customer.CustomerID);

            return CustomerMemberCard;
        }

        public static int CalculateCredits(double totalCost, Customer customer, ApplicationDbContext _context)
        {
            if (GetMemberCard(customer, _context) != null)
            {

                GetMemberCard(customer, _context).Credits = (int)(totalCost * 10) + GetMemberCard(customer, _context).Credits;

                return GetMemberCard(customer, _context).Credits;
            }
            else
            {
                return 0;
            }
        }

        public static void CheckMembershipType(MemberCard memberCard, int credits, ApplicationDbContext _context)
        {
            if (credits >= 1000 && credits <= 5000)
            {
                memberCard.Type = MembershipType.Silver;

            }
            else if (credits > 5000)
            {
                memberCard.Type = MembershipType.Gold;
            }
            else
            {
                memberCard.Type = MembershipType.Basic;
            }
            _context.SaveChanges();

        }

        public static bool CheckBonus(double totalCost, Customer customer, ApplicationDbContext _context)
        {
            if (GetMemberCard(customer, _context) != null)
            {

                if (customer.MemberCard.Type == MembershipType.Silver)
                {
                    if (totalCost > 20)
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
                else if (customer.MemberCard.Type == MembershipType.Gold)
                {
                    if (totalCost > 30)
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
                else
                {
                    return false;
                }
            }
            else
            {
                return false;
            }
        }

        public static void UpdateCredits(Customer customer, ApplicationDbContext _context, int newCredits)
        {
            if (GetMemberCard(customer, _context) != null)
            {
                GetMemberCard(customer, _context).Credits = newCredits;
                _context.SaveChanges();
            }
        }

        public static double BonusAmount(Customer customer, ApplicationDbContext _context)
        {
            if (GetMemberCard(customer, _context) != null)
            {
                var memberCard = (GetMemberCard(customer, _context));

                if (memberCard.Type == MembershipType.Basic)
                {
                    return -10;

                }
                if (memberCard.Type == MembershipType.Silver)
                {
                    return -20;
                }
                else
                {
                    return -30;
                }
            }
            else
                return 0;

        }

        public static double GetNewTotalCost(double totalcost, double bonusAmount)
        {


            return totalcost + bonusAmount;
        }

        public static void ZeroMemberPoints(Customer customer, ApplicationDbContext _context)
        {
            UpdateCredits(customer, _context, 0);
        }
    }
}

Controllers/Api/MemberCardsController.cs
using OilTeamProject.Models.Customers;
using OilTeamProject.Persistence;
using System.Data;
using System.Linq;
using System.Web.Http;

namespace OilTeamProject.Controllers.api
{
    public class MemberCardsController : ApiController
    {
        public ApplicationDbContext _context;

        public MemberCardsController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpPost]
        public IHttpActionResult Create(int? id)
        {
            if (_context.MemberCards
                .Any(m => m.CustomerID == id))
                return BadRequest("The membercard already exists");

            var memberCard = new MemberCard
            {
                CustomerID = id.Value,
                MemberCardCode = MemberCard.GetMemberCardCode(),
                Type = MembershipType.Basic,
                CreationDate = MemberCard.GetCreationDate(),
                Credits = 0
            };

            _context.MemberCards.Add(memberCard);
            _context.SaveChanges();

            return Ok();
        }

        [HttpPost]
        public IHttpActionResult Delete(int? id)
        {
            var memberCard = _context.MemberCards.Find(id);
            _context.MemberCards.Remove(memberCard);

            try
            {
                _context.SaveChanges();
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes");
            }

            return Ok();
        }
    }
}

Controllers/MemberCardsController.cs
using OilTeamProject.Models.Customers;
using OilTeamProject.Persistence;
using System.Net;
using System.Web.Mvc;

namespace OilTeamProject.Controllers
{
    public class MemberCardsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MemberCardsController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(MemberCard member, int? id)
        {

            if (!ModelState.IsValid)
            {
                return View("Create", member);
            }

            // Create a memberCard

            var memberCard = new MemberCard()
            {
                CustomerID = id.Value,
                MemberCardCode = MemberCard.GetMemberCardCode(),
                Type = MembershipType.Basic,
                CreationDate = MemberCard.GetCreationDate(),
                Credits = 0,
                NewsLetter = member.NewsLetter
            };

            // Send memberCard to DB
            _context.MemberCards.Add(memberCard);
            _context.SaveChanges();

            // where i will send the user
            return RedirectToAction("Index", "Customers");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            MemberCard memberCard = _context.MemberCards.Find(id);

            if (memberCard == null)
            {
                return HttpNotFound();
            }

            return View(memberCard);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            MemberCard memberCard = _context.MemberCards.Find(id);

            _context.MemberCards.Remove(memberCard);
            _context.SaveChanges();

            return RedirectToAction("Index", "Customers");
        }

    }
}

Views/MemberCards/Create.cshtml
@model OilTeamProject.Models.Customers.MemberCard
@{ 
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create new MemberCard</h2>
@using (Html.BeginForm("Create", "MemberCards"))
{   
        <label>
            @Html.CheckBoxFor(m => m.NewsLetter)
            Subscribed to Newsletter
        </label>
		<hr />
    @*</div>*@
    <button type="submit" class="btn btn-primary">Generate Code</button>
}





Views/MemberCards/Index.cshtml

@{
	ViewBag.Title = "Index";
}

<h2 class="text-center"></h2>

<div class="row">
		<div  class="col-lg-12 container-fluid" style="background-color:darkolivegreen;">
			<p class="membercard-benefits">MemberCard Benefits</p>
		</div>
	<div class="col-lg-4">
		<img class="col-lg-2" src="~/Image/olives.png" alt="olives" />
	</div>
</div>

<div class="row text-primary">
	<div class="col-lg-6" style="background-color:white;">	
		<img class="center-block" src="~/Image/olive-oil.png" alt="pick" />
		<p class="member">Take a look of our products and chooce what do you need</p><br />
		</div>

		<div class="col-lg-6">
			<img class="center-block" src="~/Image/discover.png" alt="discover" />
			<p class="member">Are you already a member? Perfect! If you are not a member you can easily become and win discount on your next order by using our membercard!<br /> Each <strong>1€ = 10 points</strong> <br /></p>
		</div>
</div>	

<hr class="hr-success"/>

<div class="row offer">
		<div class="col-lg-2">
			<img class="" src="~/Image/discount-tag.png" alt="discount" />
		</div>
			<div class="col-lg-10">
			<table class="table table-sm offer">
				<thead>
					<tr>
						<th scope="col">
							Card
						</th>
						<th scope="col">Points</th>
						<th scope="col">Discount</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th scope="row">Basic</th>
						<td>0 - 1.000</td>
						<td>10€</td>
					</tr>
					<tr>
						<th scope="row">Silver</th>
						<td>1.001 - 5.000</td>
						<td>20€</td>
					</tr>
					<tr>
						<th scope="row">Gold</th>
						<td>> 5.000</td>
						<td>30€</td>
					</tr>
				</tbody>
			</table>		
	</div>
</div>





