Models/Customers/CreditCard.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OilTeamProject.Models.Customers
{
    public enum CardType
    {
        Visa = 1,
        MasterCard = 2,
        AmercicanExpress = 3
    }
    public class CreditCard
    {
        [Key]
        [ForeignKey("Customer")]
        public int CustomerID { get; private set; }

        public int CreditCardNumber { get; private set; }

        public CardType Type { get; private set; }

        public DateTime ExpireDate { get; private set; }

        public virtual Customer Customer { get; set; }

        private CreditCard()
        {

        }

        public CreditCard(CardType type, int creditCardNumber, DateTime expireDate, int? customerID)
        {
            if (customerID == null)
            {
                throw new ArgumentException("CustomerID");
            }

            Type = type;
            CreditCardNumber = creditCardNumber;
            ExpireDate = expireDate;
            CustomerID = customerID.Value;
        }
    }
}

ViewModels/CreditCardForm.cs
using System;
using System.ComponentModel.DataAnnotations;
using OilTeamProject.Models.Customers;

namespace OilTeamProject.ViewModels
{
    public class CreditCardForm
    {
        public int CustomerID { get; set; }

        [Required]
        [Display(Name = "Credit Card Number")]
        public int CreditCardNumber { get; set; }

        [Required]
        [Display(Name = "Credit Card Type")]
        public CardType Type { get; set; }

        [Required]
        [Display(Name = "Expire Month")]
        public string ExpMo { get; set; }

        [Required]
        [Display(Name = "Expire Year")]
        public string ExpYr { get; set; }

        public DateTime GetDateTime()
        {
            return DateTime.Parse(string.Format("{0} {1}", ExpMo, ExpYr));
        }
    }
}

Controllers/CreditCardsController.cs
using OilTeamProject.Models.Customers;
using OilTeamProject.Persistence;
using OilTeamProject.ViewModels;
using System.Data;
using System.Net;
using System.Web.Mvc;

namespace OilTeamProject.Controllers
{
    public class CreditCardsController : Controller
    {
        private ApplicationDbContext _context;

        public CreditCardsController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Create(int id)
        {
            var creditCard = new CreditCardFormViewModel()
            {
                CustomerID = id
            };

            return View(creditCard);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreditCardFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", viewModel);
            }

            //if (id == null)
            //{
            //    return HttpNotFound();
            //}

            var newCreditCard = new CreditCard(viewModel.Type, viewModel.CreditCardNumber, viewModel.GetDateTime(), viewModel.CustomerID);

            //{
            //    CustomerID = id.Value,
            //    CreditCardNumber = viewModel.CreditCardNumber,
            //    Type = viewModel.Type,
            //    ExpireDate = viewModel.GetDateTime()
            //};

            try
            {
                _context.CreditCards.Add(newCreditCard);
                _context.SaveChanges();
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes");
            }

            return RedirectToAction("CustomerProfile", "Customers", new { id = newCreditCard.CustomerID });
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            CreditCard creditCard = _context.CreditCards.Find(id);
            if (creditCard == null)
                return HttpNotFound();

            return View(creditCard);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            CreditCard creditCard = _context.CreditCards.Find(id);

            _context.CreditCards.Remove(creditCard);
            _context.SaveChanges();
            return RedirectToAction("CustomerProfile", "Customers", new { id = creditCard.CustomerID });
        }
    }
}

Views/CreditCards/Create.cshtml
@model OilTeamProject.ViewModels.CreditCardFormViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Credit Card</h2>

<hr />

@using (Html.BeginForm("Create", "CreditCards"))
 {
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.CustomerID)

    <div class="form-group">
        @Html.LabelFor(m => m.Type)
        @Html.EnumDropDownListFor(m => m.Type, "-Select-", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Type, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.CreditCardNumber)
        @Html.TextBoxFor(m => m.CreditCardNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.CreditCardNumber, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ExpMo)
        @Html.TextBoxFor(m => m.ExpMo, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ExpMo, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ExpYr)
        @Html.TextBoxFor(m => m.ExpYr, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ExpYr, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
 }


Views/CreditCards/Delete.cshtml
@model OilTeamProject.Models.Customers.CreditCard
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>
<ul>
    <li>@Model.CreditCardNumber</li>
    <li>@Model.Type</li>
    <li>@Model.Customer.FullName</li>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions alert">
            <input type="submit" value=" Delete" class="btn btn-warning alert-danger" />
            @Html.ActionLink("Back", "Details", "Customers")
        </div>

    }

</ul>