Models/Employees/Performance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using OilTeamProject.Models;

namespace OilTeamProject.Models.Employees
{
    public class Performance
    {
        public int ID { get; set; }

        public int EmployeeID { get; set; }     
        public int EvaluationID { get; set; }
        public int FormID { get; set; }
        public decimal OveralRating { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateEvaluated { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Evaluation Evaluation { get; set; }
      
        public virtual  Form Form{ get; set; }
        public virtual ICollection<Answer> Answers { get; set; }


    }
}

Areas/Admin/Controllers/PerformancesController.cs
using OilTeamProject.Models.Employees;
using OilTeamProject.Persistence;
using OilTeamProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace OilTeamProject.Areas.Admin.Controllers
{
    public class PerformancesController : Controller
    {
        private ApplicationDbContext _context;

        public PerformancesController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Performances
        public ActionResult Index()
        {
            var performances = _context.Performances.Include(p => p.Employee).Include(p => p.Evaluation);
            return View(performances.ToList());
        }

        // GET: Performances/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Performance performance = _context.Performances.Find(id);
            if (performance == null)
            {
                return HttpNotFound();
            }
            return View(performance);
        }

        // GET: Performances/Create
        public ActionResult Create(int? formId)
        {
            

            var viewModel = new PerformanceData()
            {
                Employees = _context.Employees.ToList(),
                Evaluations = _context.Evaluations.ToList(),
                Forms = _context.Forms.ToList(),
                DateTime = DateTime.Now,
                

            };

            if (formId != null)
            {
                if (formId == 0)
                {
                    
                }
                viewModel.FormId = (int)formId;
                viewModel.Questions = viewModel.GetFormQuestions((int)formId);
            }




            return View(viewModel);
        }

        // POST: Performances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PerformanceData performanceData)
          {
            if (performanceData.FormId == 0 ||  
                performanceData.Evaluation.ID == 0 ||
                performanceData.Employee.Id == 0)
            {
                performanceData.Evaluations = _context.Evaluations.ToList();
                performanceData.Employees = _context.Employees.ToList();
                performanceData.Forms = _context.Forms.ToList();



                return View("Create", performanceData);
            }
            
            var performance = new Performance()
            {
                FormID = performanceData.FormId,
                EmployeeID = performanceData.Employee.Id,
                EvaluationID = performanceData.Evaluation.ID,
                DateEvaluated = DateTime.Now,
                

            };
            performance.OveralRating = OverallRatingCalculate(performanceData.Answers);




            if(_context.Performances.Any(p => p.EmployeeID == performance.EmployeeID && p.EvaluationID == performance.EvaluationID))
            {
                performanceData.ExistingPerformance = true;
                performanceData.Forms = _context.Forms;
                performanceData.Employees = _context.Employees;
                performanceData.Evaluations = _context.Evaluations.ToList();
                performanceData.Questions = performanceData.GetFormQuestions(performanceData.FormId);
                return View("Create", performanceData);
            }

            _context.Performances.Add(performance);
            _context.SaveChanges();

            for (int i = 0; i < performanceData.Questions.Count; i++)
            {
                performanceData.Answers[i].QuestionID = performanceData.Questions[i].ID;
            }

            foreach (var answer in performanceData.Answers)
            {
                answer.PerformanceID = performance.ID;
                _context.Answers.Add(answer);
            }
            _context.SaveChanges();

            return RedirectToAction("Index", "Evaluations");
        }

        public int OverallRatingCalculate(List<Answer> answers)
        {
            int allValuesOfAnswers = 0;
            foreach ( var answer in answers)
            {
                allValuesOfAnswers += (int)answer.QuestionAnswer;
            }

            var finalRating = allValuesOfAnswers / answers.Count();
            finalRating = finalRating * 100 / 5;
            return finalRating;
        }

        // GET: Performances/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Performance performance = _context.Performances.Find(id);
            if (performance == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeID = new SelectList(_context.Employees, "ID", "Name", performance.EmployeeID);
            ViewBag.EvaluationID = new SelectList(_context.Evaluations, "EvaluationID", "EvaluationID", performance.EvaluationID);
            return View(performance);
        }

        // POST: Performances/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,EmployeeID,EvaluationID,OveralRating,DateEvaluated")] Performance performance)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(performance).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeID = new SelectList(_context.Employees, "ID", "Name", performance.EmployeeID);
            ViewBag.EvaluationID = new SelectList(_context.Evaluations, "EvaluationID", "EvaluationID", performance.EvaluationID);
            return View(performance);
        }

        // GET: Performances/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Performance performance = _context.Performances.Find(id);
            if (performance == null)
            {
                return HttpNotFound();
            }
            return View(performance);
        }

        // POST: Performances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Performance performance = _context.Performances.Find(id);
            _context.Performances.Remove(performance);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/FormsController.cs
using OilTeamProject.Models;
using OilTeamProject.Models.Employees;
using OilTeamProject.Persistence;
using OilTeamProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace OilTeamProject.Controllers
{
    public class FormsController : Controller
    {
        private ApplicationDbContext _context;

        public FormsController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Forms
        public ActionResult Index()
        {


            return View();
        }

        [HttpGet]
        public ActionResult Create(bool? createNewQuestion)
        {
            var questions = _context.Questions.ToList();

            var viewModel = new EvaluationsData();

            //viewModel.Questions = questions;

            //foreach (var item in questions)
            //{
            //    viewModel.SelectedQuestions = new List<SelectListItem>
            //    {
            //        new SelectListItem {Text = item.Text, Value = item.ID.ToString()}
            //    };
            //}

            var selectedQuestions = new List<SelectListItem>();



            foreach (var item in questions)
            {
                selectedQuestions.Add(new SelectListItem { Text = item.Text, Value = item.ID.ToString() });
            }


            viewModel.SelectedQuestions = selectedQuestions;

            //if (createNewQuestion == true)
            //{
            //    ViewBag.NewQuestionTextBox = viewModel.CreateNewQuestion;
            //}


            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EvaluationsData viewModel)
        {
            var questionsFromViewModel = new List<Question>();
            var questions = _context.Questions.ToList();

            viewModel.CheckedQuestions.ToList();
            foreach (var item in viewModel.CheckedQuestions)
            {
                var itemNumber = Int32.Parse(item);
                var questionIDs = _context.Questions.Find(itemNumber);
                questionsFromViewModel.Add(questionIDs);
            }


            var form = new Form()
            {
                Theme = viewModel.Form.Theme,
                Questions = questionsFromViewModel

            };

            _context.Forms.Add(form);
            _context.SaveChanges();

            return RedirectToAction("Create", "Performances");
        }



        //[HttpPost]
        //public ActionResult Create(EvaluationsData evaluationsData, FormCollection fc)
        //{
        //    string text = fc["txttest"];


        //    return RedirectToAction("Create", "Performances");
        //}
    }
}

Views/Performances/Create.cshtml
@model OilTeamProject.ViewModels.PerformanceData

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create New Performance</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    if (Model.ExistingPerformance == true)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                X
            </button>
            Performance already exists
        </div>
    }
    <div>
        <div class="form-group">
            @Html.ActionLink("Create New Form", "Create", "Forms")
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Form, "Form Type", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.FormId, new SelectList(Model.Forms, "ID", "Theme"), "Select", htmlAttributes: new { onchange = @"CallChangefunc(this.value)", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Form, "", new { @class = "text-danger" })\
            @Html.HiddenFor(model => model.FormId)
            
            <script>
                function CallChangefunc(val) {
                    window.location.href = " /Performances/Create?formId=" + val;
                }
            </script>


        </div>

        @*<div class="form-group">
            @Html.DropDownListFor(model => model.FormId, new SelectList(Model.Forms, "ID", "Theme"), "Select", htmlAttributes: new { onchange = @"CallChangefunc(this.value)", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Form, "", new { @class = "text-danger" })
            <script>
                function CallChangefunc(val) {
                    window.location.href = " /Performances/Create?formId=" + val;
                }
            </script>

        </div>*@
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
        <div class="form-group">
            @Html.LabelFor(model => model.Employee, "Employee", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.Employee.Id, new SelectList(Model.Employees, "ID", "FullName"), "Select", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Employee, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Employee.Id)
            
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Evaluation, "Evaluation", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownListFor(model => model.Evaluation.ID, new SelectList(Model.Evaluations, "ID", "EvaluationDate"), "Select", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Evaluation, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Evaluation.ID)
            
        </div>

        <div class="form-group">
            @if (Model.FormId != 0)
            {
                <table>
                    @for (int i = 0; i < Model.Questions.Count(); i++)
                    {

                        <tr class="form-group">
                            <td class="form-group col-md-4">
                                @Html.DisplayFor(m => m.Questions[i].Text, new { @class = "control-label col-sm-4" }) @Html.HiddenFor(m => m.Questions[i].ID)
                            </td>
                            <td class="form-group col-md-6">
                                @Html.EnumDropDownListFor(a => a.Answers[i].QuestionAnswer, "Select", new { @class = "form-control" })<br />
                                @Html.ValidationMessageFor(model => model.Answers, "", new { @class = "text-danger" })
                            </td>
                        </tr>

                    }
                </table>
            }
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

}


