Models/Customers/CreditCard.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OilTeamProject.Models.Customers
{
    public enum CardType
    {
        Visa = 1,
        MasterCard = 2,
        AmercicanExpress = 3
    }
    public class CreditCard
    {
        [Key]
        [ForeignKey("Customer")]
        public int CustomerID { get; private set; }

        public int CreditCardNumber { get; private set; }

        public CardType Type { get; private set; }

        public DateTime ExpireDate { get; private set; }

        public virtual Customer Customer { get; set; }

        private CreditCard()
        {

        }

        public CreditCard(CardType type, int creditCardNumber, DateTime expireDate, int? customerID)
        {
            if (customerID == null)
            {
                throw new ArgumentException("CustomerID");
            }

            Type = type;
            CreditCardNumber = creditCardNumber;
            ExpireDate = expireDate;
            CustomerID = customerID.Value;
        }
    }
}

Models/Customers/Customer.cs
using OilTeamProject.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OilTeamProject.Models.Customers
{
    public enum ActivityStatus
    {
        Active = 1,
        Inactive = 2
    }

    public enum CommercialType
    {
        Leisure = 1,
        Industrial = 2,
        HealthCare = 3,
        Hospitality = 4
    }

    public enum Gender
    {
        Male = 1,
        Female = 2
    }

    public class Customer
    {
        public int CustomerID { get; set; }

        public ActivityStatus ActivityStatus { get; set; }

        [Required]
        [Display(Name = "First Νame")]
        [StringLength(30, ErrorMessage = "'First Name' must be between 3-30 characters long", MinimumLength = 3)]
        public string FirstName { get; private set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(30, ErrorMessage = "'Last Name' must be between 3-30 characters long", MinimumLength = 3)]
        public string LastName { get; private set; }

        [Display(Name = "Company")]
        [StringLength(50, ErrorMessage = "'Company Name' must be between 3-30 characters long", MinimumLength = 3)]
        public string CompanyName { get; private set; }

        [Display(Name = "Company Type")]
        public CommercialType? CompanyType { get; private set; }

        [Required]
        public Gender Gender { get; private set; }

        [Required]
        [Display(Name = "Date of Birth")]
        //[ValidDate]
        public DateTime DateOfBirth { get; private set; }

        [Required]
        [StringLength(30, ErrorMessage = "'Country' must be between 3-30 characters long", MinimumLength = 3)]
        public string Country { get; private set; }

        [Required]
        [StringLength(30, ErrorMessage = "'City' must be between 3-30 characters long", MinimumLength = 3)]
        public string City { get; private set; }

        [Required]
        [StringLength(40, ErrorMessage = "'Address' must be between 3-30 characters long", MinimumLength = 3)]
        public string Address { get; private set; }

        [Required]
        [Display(Name = "Postal Code")]
        [DataType(DataType.PostalCode)]
        public int PostalCode { get; private set; }

        [Required]
        [Display(Name = "Phone")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; private set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; private set; }

        public DateTime CreationDate { get; private set; }

        public virtual CreditCard CreditCard { get; private set; }
        public virtual ICollection<Order> Orders { get; private set; }
        public virtual MemberCard MemberCard { get; private set; }

        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

        public DateTime GetCreationDate()
        {
            return CreationDate = DateTime.Now;
        }

        public Customer()
        {

        }

        public Customer(ActivityStatus status, string firstName, string lastName, string companyName,
                        CommercialType? type, Gender gender, DateTime dateOfBirth, string country,
                        string city, string address, int postalCode, string phoneNumber, string email,
                        DateTime creationDate)
        {
            ActivityStatus = status;
            FirstName = firstName;
            LastName = lastName;
            CompanyName = companyName;
            CompanyType = type;
            Gender = gender;
            DateOfBirth = dateOfBirth;
            Country = country;
            City = city;
            Address = address;
            PostalCode = postalCode;
            PhoneNumber = phoneNumber;
            Email = email;
            CreationDate = GetCreationDate();
        }

        public static Customer Create(CustomerFormViewModel viewModel)
        {
            if (viewModel == null)
            {
                throw new ArgumentNullException("viewModel");
            }

            return new Customer(ActivityStatus.Active, viewModel.FirstName, viewModel.LastName, viewModel.CompanyName,
                                viewModel.CompanyType, viewModel.Gender, viewModel.DateOfBirth, viewModel.Country,
                                viewModel.City, viewModel.Address, viewModel.PostalCode, viewModel.PhoneNumber, viewModel.Email,
                                viewModel.CreationDate);
        }

        public static Customer Modify(Customer customer, CustomerFormViewModel viewModel)
        {
            if (viewModel == null)
            {
                throw new ArgumentNullException("viewModel");
            }

            if (customer == null)
            {
                throw new ArgumentNullException("customer");
            }

            customer.FirstName = viewModel.FirstName;
            customer.LastName = viewModel.LastName;
            customer.CompanyName = viewModel.CompanyName;
            customer.CompanyType = viewModel.CompanyType;
            customer.Gender = viewModel.Gender;
            customer.DateOfBirth = viewModel.DateOfBirth;
            customer.Country = viewModel.Country;
            customer.City = viewModel.City;
            customer.Address = viewModel.Address;
            customer.PostalCode = viewModel.PostalCode;
            customer.PhoneNumber = viewModel.PhoneNumber;
            customer.Email = viewModel.Email;

            return customer;
        }

        public static Customer Remove(Customer customer)
        {
            if (customer == null)
            {
                throw new ArgumentNullException("customer");
            }

            customer.ActivityStatus = ActivityStatus.Inactive;

            return customer;
        }
    }
}

Models/Customers/PaymentType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OilTeamProject.Models.Customers
{  
        public enum PaymentType
        {
            CreditCard = 1,
            Cash = 2,
            COD = 3, // CASH ON DELIVERY
            none = 4
        }
    
}

Controllers/Api/CustomersController.cs
using OilTeamProject.Models;
using OilTeamProject.Models.Customers;
using OilTeamProject.Persistence;
using System.Data;
using System.Linq;
using System.Web.Http;

namespace OilTeamProject.Controllers.api
{
    public class CustomersController : ApiController
    {
        public ApplicationDbContext _context;

        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpPost]
        public IHttpActionResult Remove(int? id)
        {
            var customer = _context.Customers
                .Single(c => c.CustomerID == id && c.ActivityStatus == ActivityStatus.Active);
            Customer.Remove(customer);

            try
            {
                _context.SaveChanges();
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes");
            }

            return Ok();
        }

        [HttpPost]
        public IHttpActionResult Delete(int? id)
        {
            var customer = _context.Customers.Find(id);

            _context.Customers.Remove(customer);

            try
            {
                _context.SaveChanges();
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes");
            }

            return Ok();
        }
    }
}

Controllers/OrdersController.cs
using OilTeamProject.Models.Customers;
using OilTeamProject.Models.Products;
using OilTeamProject.Persistence;
using OilTeamProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OilTeamProject.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext _context;

        public OrdersController()
        {
            _context = new ApplicationDbContext();
        }



        public ActionResult PayOff(int? id)
        {
            var UnpaidOrder = _context.Orders
                .Where(o => o.OrderID == id)
                .Include(o => o.OrderProducts)
                .Include(o => o.Customer)
                .Single();

            var viewModel = UnpaidOrder.FillOrderDetailsViewModel(UnpaidOrder, _context);
            return View("OrderReceiptUpdated", viewModel);
        }

        [HttpPost]
        public ActionResult PayOff(OrderDetailsFormViewModel viewModel)
        {
            var Order = _context.Orders.Find(viewModel.OrderId);
            if (viewModel.PaymentType != PaymentType.none)
            {
                Order.PaymentType = viewModel.PaymentType;
                Order.PaidOff = Order.CheckpaidOffProperty(Order.PaymentType);
                Order.PaymentDate = DateTime.Now;
                _context.SaveChanges();
            }


            return RedirectToAction("PendingOrders", new { id = Order.CustomerId });
        }
        public ActionResult PendingOrders(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var CustomerPendingOrders = _context.Orders
                .Where(o => o.CustomerId == id && !o.PaidOff)
                .ToList();


            ViewBag.ListCount = Order.CountPendingOrders(CustomerPendingOrders);
            return View(CustomerPendingOrders);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var Order = _context.Orders.Find(id);

            return View(Order);
        }

        public ActionResult EditDetails(int? id)
        {
            var newOrder = _context.Orders
                .Include(o => o.OrderProducts)
                .Where(o => o.OrderID == id)
                .Single();

            OrderFormViewModel viemodel = Order.PopulateUpdateOrderDetails(newOrder, _context);
            return View(viemodel);
        }

        [HttpPost]
        public ActionResult EditDetails(OrderFormViewModel viewModel)
        {


            //if (!ModelState.IsValid)
            //{
            //    return View("EditDetails", viewModel);
            //}

            var OrderToUpdate = _context.Orders
                .Include(o => o.OrderProducts)
                .Where(O => O.OrderID == viewModel.OrderId)
                .Single();





            Order.UpdateOrderProducts(OrderToUpdate, viewModel, _context);
            _context.SaveChanges();
            return RedirectToAction("Details", new { id = viewModel.OrderId });




            //PopulateUpdateOrderDetails(OrderToUpdate);

            //return View(OrderToUpdate);





        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Order order = _context.Orders
               .Include(o => o.OrderProducts)
               .Where(o => o.OrderID == id)
               .Single();





            if (order == null)
            {
                return HttpNotFound();
            }

            return View(order);
        }


        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = _context.Orders.Find(id);
            //order.TotalCost = Order.GetTotalCost(order.OrderID, db);


            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int Id)
        {
            try
            {
                Order.DeleteOrder(Id, _context);

            }
            catch (Exception)
            {
                ModelState.AddModelError("", "unable to save changes");
            }
            //Order order = db.Orders.Find(id);
            //db.Orders.Remove(order);
            //db.SaveChanges();
            return RedirectToAction("Index", "Customers");
        }


        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var customer = _context.Customers.Find(id);
            var ViewModel = Order.FillOrderFormViewModel(_context);

            ViewModel.CustomerId = customer.CustomerID;
            return View("ShoppingCart", ViewModel);
        }


        [HttpPost]
        public ActionResult Create(OrderFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", viewModel);
            }



            var customer = _context.Customers.Find(viewModel.CustomerId);

            OrderDetailsFormViewModel detailsViewModel = Order.FillOrderDetailsViewModel(viewModel, customer, _context);

            return View("OrderReceiptUpdated", detailsViewModel);
        }


        [HttpPost]
        public ActionResult ConfirmOrder(OrderDetailsFormViewModel viewModel)
        {

            if (viewModel.TotalCost == 0)
            {
                viewModel.CartIsEmpty = true;
                viewModel.OrderDate = DateTime.Now;
                return View("OrderReceipt", viewModel);
            }

            var customer = _context.Customers.Find(viewModel.CustomerId);

            Order order = new Order(Order.GetOrderNumber(viewModel.CustomerId, _context)
               , Order.CheckpaidOffProperty(viewModel.PaymentType)
               , Order.RedeemOrNot(viewModel, customer, _context),
               viewModel.PaymentType, customer,
               Order.SetOrderStatus(Order.CheckpaidOffProperty(viewModel.PaymentType)),
               Order.SetPayDate(Order.CheckpaidOffProperty(viewModel.PaymentType)));

            OrderProducts orderProducts = new OrderProducts();




            _context.Orders.Add(order);
            _context.SaveChanges();


            for (int i = 0; i < viewModel.Count; i++)
            {
                if (viewModel.AddToCarts[i] && viewModel.Quantities[i] != 0)
                {

                    orderProducts.OrderID = order.OrderID;
                    orderProducts.ProductStockID = viewModel.ProductStockIds[i];
                    orderProducts.Quantity = viewModel.Quantities[i];

                    _context.OrderProducts.Add(orderProducts);

                    var ProductStockToUpdate = _context.ProductStocks.Single(p => p.ProductStockID == orderProducts.ProductStockID);
                    ProductStockToUpdate = ProductStockToUpdate.SendProductStock(viewModel.Quantities[i], orderProducts.ProductStockID);


                    _context.Set<ProductStock>().AddOrUpdate(ProductStockToUpdate);
                    _context.SaveChanges();
                }
            }


            if (customer.MemberCard != null)
            {
                if (viewModel.RedeemBonus)
                {
                    MemberCard.ZeroMemberPoints(customer, _context);
                }
                else
                {
                    MemberCard.UpdateCredits(customer, _context, MemberCard.CalculateCredits(order.TotalCost, customer, _context));
                }

                MemberCard.CheckMembershipType(customer.MemberCard, customer.MemberCard.Credits, _context);
            }

            return RedirectToAction("Index", "Customers");




        }

    }
}

Views/Customers/CustomerProfile.cshtml
@model OilTeamProject.ViewModels.CustomerProfileViewModel

@{
	ViewBag.Title = "Profile";
	Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>@Html.DisplayFor(m => m.FullName)</h2>

<div class="container">
	<div class="row">

		<div class="col-sm-3">

			<div class="text-center">

				<img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
				<h6>Upload a different photo...</h6>
				<input type="file" class="text-center center-block file-upload">

			</div>
			<hr />
			<br>

			<ul class="list-group">

				<li class="list-group-item text-muted">
					Orders
				</li>


				<li class="list-group-item text-right">
					<span class="pull-left">
						<strong>
							@Html.DisplayNameFor(m => m.FulfilledOrders)
						</strong>
					</span>
					@Html.DisplayFor(m => m.FulfilledOrders)
				</li>

				<li class="list-group-item text-right">
					<span class="pull-left">
						<strong>
							@Html.DisplayNameFor(m => m.DeletedOrders)
						</strong>
					</span>
					@Html.DisplayFor(m => m.DeletedOrders)
				</li>

				<li class="list-group-item text-right">
					<span class="pull-left">
						<strong>
							@Html.DisplayNameFor(m => m.InProgressOrders)
						</strong>
					</span>
					@Html.DisplayFor(m => m.InProgressOrders)
				</li>

				<li class="list-group-item text-right">
					<span class="pull-left">
						<strong>
							@Html.DisplayNameFor(m => m.TotalOrders)
						</strong>
					</span>
					@Html.DisplayFor(m => m.TotalOrders)
				</li>

			</ul>


			<div class="row">

				<div class="col-md-12">

					<div class="col-md-6">

						<span>
							<a href="@Url.Action("OrdersHistory", "Customers" , new { id=Model.CustomerID } )" class="btn btn-info">
								Show Orders
							</a>
						</span>

					</div>

					<div class="col-md-6">

						<span>
							<a href="@Url.Action("Create", "Orders" , new { id=Model.CustomerID } )" class="btn btn-primary">
								New Order
							</a>
						</span>

					</div>

				</div>

			</div>

		</div>

		<div class="col-sm-9">
			<ul class="nav nav-tabs">

				<li class="active">
					<a data-toggle="tab" href="#profile">
						Personal Details
					</a>
				</li>
				<li>
					<a data-toggle="tab" href="#membership">
						Membership
					</a>
				</li>

			</ul>

			<div class="tab-content">

				<div class="tab-pane active" id="profile">
					<hr>
					<form class="form">

						<div class="form-group">
							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.FirstName)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.FirstName)
								</label>
							</div>
						</div>

						<div class="form-group">
							<div class="col-xs-6">

								<label class="h4">
									@Html.DisplayNameFor(model => model.LastName)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.LastName)
								</label>
							</div>
						</div>

						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.Gender)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.Gender)
								</label>
							</div>
						</div>

						<div class="form-group">
							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.DateOfBirth)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.DateOfBirth)
								</label>
							</div>
						</div>
						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.CompanyName)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.CompanyName)
								</label>
							</div>
						</div>
						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.CompanyType)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.CompanyType)
								</label>
							</div>
						</div>
						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.Country)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.Country)
								</label>
							</div>
						</div>
						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.City)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.City)
								</label>
							</div>
						</div>

						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.Address)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.Address)
								</label>
							</div>
						</div>

						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.PostalCode)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.PostalCode)
								</label>
							</div>
						</div>
						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.PhoneNumber)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.PhoneNumber)
								</label>
							</div>
						</div>
						<div class="form-group">

							<div class="col-xs-6">
								<label class="h4">
									@Html.DisplayNameFor(model => model.Email)
								</label>
								<label type="text" class="form-control">
									@Html.DisplayFor(model => model.Email)
								</label>
							</div>
						</div>


						<div class="form-group">
							<div class="col-xs-12">
								<br>

								<span class="actions">

									<a href="@Url.Action("Edit", "Customers", new { id = Model.CustomerID})" class="btn  btn-warning">
										<span class="glyphicon glyphicon-edit"></span>
										Edit
									</a>

								</span>

								<span class="actions">

									<a href="#" data-customer-id="@Model.CustomerID" class="btn btn-danger js-remove-customer">
										<span class="glyphicon glyphicon-trash"></span>
										Remove
									</a>

								</span>

								<span class="actions">

									<a href="#" data-customer-id="@Model.CustomerID" class="btn btn-danger js-delete-customer">
										<span class="glyphicon glyphicon-remove"></span>
										Delete
									</a>

								</span>

							</div>
						</div>

					</form>

					<hr>

				</div>

				<div class="tab-pane" id="membership">
					<hr>

					@if (Model.MemberCard == null)
					{
					<div class="row text-center">
						
						<a href=@Url.Action("Create", "MemberCards", new { id = Model.CustomerID}) class="btn btn-success js-create-membercard">
							<span class="glyphicon glyphicon-credit-card"></span>
							Create memberCard
						</a>
					</div>
					}
					else
					{
						<form class="form">

							<div class="form-group">
								<div class="col-xs-6">
									<label class="h4">
										@Html.DisplayNameFor(model => model.MemberCard.CreationDate)
									</label>
									<label type="text" class="form-control">
										@Html.DisplayFor(model => model.MemberCard.CreationDate)
									</label>
								</div>
							</div>

							<div class="form-group">
								<div class="col-xs-6">

									<label class="h4">
										@Html.DisplayNameFor(model => model.MemberCard.MemberCardCode)
									</label>
									<label type="text" class="form-control">
										@Html.DisplayFor(model => model.MemberCard.MemberCardCode)
									</label>
								</div>
							</div>

							<div class="form-group">

								<div class="col-xs-6">
									<label class="h4">
										@Html.DisplayNameFor(model => model.MemberCard.Type)
									</label>
									<label type="text" class="form-control">
										@Html.DisplayFor(model => model.MemberCard.Type)
									</label>
								</div>
							</div>

							<div class="form-group">

								<div class="col-xs-6">
									<label class="h4">
										@Html.DisplayNameFor(model => model.MemberCard.Credits)
									</label>
									<label type="text" class="form-control">
										@Html.DisplayFor(model => model.MemberCard.Credits)
									</label>
								</div>
							</div>


							<div class="form-group">
								<div class="col-xs-12">
									<br>

									<span class="actions">
										<a href="#" data-customer-id="@Model.CustomerID" class="btn btn-danger js-delete-membercard">
											<span class="glyphicon glyphicon-remove"></span>
											Delete
										</a>
										@*@*<a href="@Url.Action("Delete", "MemberCards", new { id = Model.CustomerID})" class="btn btn-danger js-delete-membercard">*@
										@*<span class="glyphicon glyphicon-trash"></span>
										Delete
										</a>*@

									</span>
								</div>
							</div>

						</form>

					}
					<hr>
				</div>

			</div>
		</div>
	</div>

</div>
@section scripts
{
	<script>
		$(document).ready(function (){

			$(".js-remove-customer").click(function (e) {
				var link = $(e.target);

				bootbox.dialog({
					title: 'Confirm',
					message: "<h4>Are you sure you want to remove this customer?</h4>",

					buttons: {
						no: {
							label: "No",
							className: 'btn-default',
							callback: function () {
								bootbox.hideAll();
							}
						},
						yes: {
							label: "Yes",
							className: 'btn-danger',
							callback: function () {
								$.ajax({
									url: "/api/customers/remove/" + link.attr("data-customer-id"),
									method: "POST"
								})
									.done(function () {
										window.location.href = '/Customers/Index/';
										//alert("The customer was removed successfully.")
									})
									.fail(function () {
										alert("Something failed")
									});
							}
						}
					}
				});
			});

			$(".js-delete-customer").click(function (e) {
				var link = $(e.target);

				bootbox.dialog({
					title: 'Confirm',
					message: "<h4>Are you sure you want to delete this customer?</h4>",

					buttons: {
						no: {
							label: "No",
							className: 'btn-default',
							callback: function () {
								bootbox.hideAll();
							}
						},
						yes: {
							label: "Yes",
							className: 'btn-danger',
							callback: function () {
								$.ajax({
									url: "/api/customers/delete/" + link.attr("data-customer-id"),
									method: "POST"
								})
									.done(function () {
										window.location.href = '/Customers/Index/';
									})
									.fail(function () {
										alert("Something failed.")
									});
							}
						}
					}
				});
			});

			$(".js-delete-membercard").click(function (e) {
				var link = $(e.target);

				bootbox.dialog({
					title: 'Confirm',
					message: "<h4>Are you sure you want to delete this membercard?</h4>",

					buttons: {
						no: {
							label: "No",
							className: 'btn-default',
							callback: function () {
								bootbox.hideAll();
							}
						},
						yes: {
							label: "Yes",
							className: 'btn-danger',
							callback: function () {
								$.ajax({
									url: "/api/membercards/delete/" + link.attr("data-customer-id"),
									method: "POST"
								})
									.done(function () {
										window.location.href = '/Customers/Index/';
									})
									.fail(function () {
										alert("Something failed.")
									});
							}
						}
					}
				});
			});
		});

	</script>
}   



